### ISSUE TITLE
Builds with Feature Branches enabled are not supported

### ISSUE THREAD

**Issue by dislogical** [jorgenpt/teamcity-ugs-status-publisher#2]
When a build with Feature Branches enabled runs, TeamCity shows the following error message (redacted where necessary):

```
Commit Status Publisher has failed to publish publishBuildStatus.buildFinished status. Publisher: ugs. For input string: "Main|18112"

Commit Status Publisher HTTP request has failed. Publisher: ugs(https://<rugs-url>/api/build). HTTP response error, response code: 500, reason: Internal Server Error
```

That error appears to include the Stream the build was run against (`Main`), and the changelist for the build that ran (`18112`).

Let me know if there's any other info I can provide to help track this down!

**Comment by jorgenpt** [comment]
@ColdenCullen And it works without Feature Branches? We don't use that functionality here (we use [DSL Context Parameters](https://www.jetbrains.com/help/teamcity/kotlin-dsl.html#contextParameters) and just re-use the config per-branch), so I'll need to set up a test case locally to reproduce / debug this.

**Comment by dislogical** [comment]
Yes it works great without feature branches! It's just the project with feature branches enabled that reports the failures.

**Comment by jorgenpt** [comment]
It's been pretty busy at work so I haven't had a chance to pursue this earlier. I sat down to do it tonight, but wasted a couple of hours setting up TeamCity & RUGS test instances in EC2. The first instance wasn't beefy enough to boot TC, the second instance was fine but couldn't sync Perforce because there aren't ARM binaries of the `p4` cli. Between all that & configuring a Perforce test server, I decided to call it for the night -- I'll get a test environment set up at some point so I can actually reproduce this and get a fix together.

**Comment by dislogical** [comment]
Just took a look at the RUGS logs and noticed these lines (`{PROJECTNAME}` is my redaction):
```
[2m2023-10-08T19:03:11.371453Z[0m [31mERROR[0m [2mrugs::error[0m[2m:[0m Internal server error: Invalid project name format <default>/{PROJECTNAME}, should be Perforce stream path to directory
```
Looks like TeamCity is passing along `<default>` when we expect the actual branch name? I wonder if there's some way to detect that and query the default branch's name?
